// Generated by CoffeeScript 2.3.0
var emitBadImports, path, wch;

path = require('path');

wch = require('wch');

emitBadImports = function(err) {
  var file, files;
  files = {};
  err.imports.forEach(function(dep) {
    var events, name;
    events = files[name = dep.parent] || (files[name] = []);
    events.push({
      file: path.join(err.root, dep.parent),
      line: dep.line - 1,
      message: `Cannot find module: '${dep.ref}'`
    });
  });
  for (file in files) {
    wch.emit('file:error', files[file]);
  }
};

module.exports = function(log) {
  var cdn;
  cdn = require('cush-cdn')();
  cdn.on('error', function(err) {
    if (err.code === 'BAD_IMPORTS') {
      return emitBadImports(err);
    }
    return log.error(err);
  });
  return {
    attach: function(pack) {
      return cdn.loadProject(pack.path);
    },
    detach: function(pack) {
      return cdn.dropProject(pack.path);
    },
    stop: function() {
      return cdn.close();
    }
  };
};
